// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package com.yametech.yangjian.agent.protocol;

public interface ReportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
