// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package com.yametech.yangjian.agent.protocol;

/**
 * <pre>
 * 上报请求实体类
 * </pre>
 *
 * Protobuf type {@code ReportRequest}
 */
public  final class ReportRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReportRequest)
    ReportRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportRequest.newBuilder() to construct.
  private ReportRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportRequest() {
    reportEntity_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReportRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              reportEntity_ = new java.util.ArrayList<com.yametech.yangjian.agent.protocol.ReportEntity>();
              mutable_bitField0_ |= 0x00000001;
            }
            reportEntity_.add(
                input.readMessage(com.yametech.yangjian.agent.protocol.ReportEntity.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        reportEntity_ = java.util.Collections.unmodifiableList(reportEntity_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yametech.yangjian.agent.protocol.ReportProto.internal_static_ReportRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yametech.yangjian.agent.protocol.ReportProto.internal_static_ReportRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yametech.yangjian.agent.protocol.ReportRequest.class, com.yametech.yangjian.agent.protocol.ReportRequest.Builder.class);
  }

  public static final int REPORTENTITY_FIELD_NUMBER = 1;
  private java.util.List<com.yametech.yangjian.agent.protocol.ReportEntity> reportEntity_;
  /**
   * <code>repeated .ReportEntity reportEntity = 1;</code>
   */
  public java.util.List<com.yametech.yangjian.agent.protocol.ReportEntity> getReportEntityList() {
    return reportEntity_;
  }
  /**
   * <code>repeated .ReportEntity reportEntity = 1;</code>
   */
  public java.util.List<? extends com.yametech.yangjian.agent.protocol.ReportEntityOrBuilder> 
      getReportEntityOrBuilderList() {
    return reportEntity_;
  }
  /**
   * <code>repeated .ReportEntity reportEntity = 1;</code>
   */
  public int getReportEntityCount() {
    return reportEntity_.size();
  }
  /**
   * <code>repeated .ReportEntity reportEntity = 1;</code>
   */
  public com.yametech.yangjian.agent.protocol.ReportEntity getReportEntity(int index) {
    return reportEntity_.get(index);
  }
  /**
   * <code>repeated .ReportEntity reportEntity = 1;</code>
   */
  public com.yametech.yangjian.agent.protocol.ReportEntityOrBuilder getReportEntityOrBuilder(
      int index) {
    return reportEntity_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < reportEntity_.size(); i++) {
      output.writeMessage(1, reportEntity_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < reportEntity_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, reportEntity_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yametech.yangjian.agent.protocol.ReportRequest)) {
      return super.equals(obj);
    }
    com.yametech.yangjian.agent.protocol.ReportRequest other = (com.yametech.yangjian.agent.protocol.ReportRequest) obj;

    if (!getReportEntityList()
        .equals(other.getReportEntityList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getReportEntityCount() > 0) {
      hash = (37 * hash) + REPORTENTITY_FIELD_NUMBER;
      hash = (53 * hash) + getReportEntityList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yametech.yangjian.agent.protocol.ReportRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yametech.yangjian.agent.protocol.ReportRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yametech.yangjian.agent.protocol.ReportRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 上报请求实体类
   * </pre>
   *
   * Protobuf type {@code ReportRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReportRequest)
      com.yametech.yangjian.agent.protocol.ReportRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yametech.yangjian.agent.protocol.ReportProto.internal_static_ReportRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yametech.yangjian.agent.protocol.ReportProto.internal_static_ReportRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yametech.yangjian.agent.protocol.ReportRequest.class, com.yametech.yangjian.agent.protocol.ReportRequest.Builder.class);
    }

    // Construct using com.yametech.yangjian.agent.protocol.ReportRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getReportEntityFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (reportEntityBuilder_ == null) {
        reportEntity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        reportEntityBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yametech.yangjian.agent.protocol.ReportProto.internal_static_ReportRequest_descriptor;
    }

    @java.lang.Override
    public com.yametech.yangjian.agent.protocol.ReportRequest getDefaultInstanceForType() {
      return com.yametech.yangjian.agent.protocol.ReportRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.yametech.yangjian.agent.protocol.ReportRequest build() {
      com.yametech.yangjian.agent.protocol.ReportRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yametech.yangjian.agent.protocol.ReportRequest buildPartial() {
      com.yametech.yangjian.agent.protocol.ReportRequest result = new com.yametech.yangjian.agent.protocol.ReportRequest(this);
      int from_bitField0_ = bitField0_;
      if (reportEntityBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          reportEntity_ = java.util.Collections.unmodifiableList(reportEntity_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.reportEntity_ = reportEntity_;
      } else {
        result.reportEntity_ = reportEntityBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yametech.yangjian.agent.protocol.ReportRequest) {
        return mergeFrom((com.yametech.yangjian.agent.protocol.ReportRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yametech.yangjian.agent.protocol.ReportRequest other) {
      if (other == com.yametech.yangjian.agent.protocol.ReportRequest.getDefaultInstance()) return this;
      if (reportEntityBuilder_ == null) {
        if (!other.reportEntity_.isEmpty()) {
          if (reportEntity_.isEmpty()) {
            reportEntity_ = other.reportEntity_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureReportEntityIsMutable();
            reportEntity_.addAll(other.reportEntity_);
          }
          onChanged();
        }
      } else {
        if (!other.reportEntity_.isEmpty()) {
          if (reportEntityBuilder_.isEmpty()) {
            reportEntityBuilder_.dispose();
            reportEntityBuilder_ = null;
            reportEntity_ = other.reportEntity_;
            bitField0_ = (bitField0_ & ~0x00000001);
            reportEntityBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReportEntityFieldBuilder() : null;
          } else {
            reportEntityBuilder_.addAllMessages(other.reportEntity_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yametech.yangjian.agent.protocol.ReportRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yametech.yangjian.agent.protocol.ReportRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.yametech.yangjian.agent.protocol.ReportEntity> reportEntity_ =
      java.util.Collections.emptyList();
    private void ensureReportEntityIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        reportEntity_ = new java.util.ArrayList<com.yametech.yangjian.agent.protocol.ReportEntity>(reportEntity_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yametech.yangjian.agent.protocol.ReportEntity, com.yametech.yangjian.agent.protocol.ReportEntity.Builder, com.yametech.yangjian.agent.protocol.ReportEntityOrBuilder> reportEntityBuilder_;

    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public java.util.List<com.yametech.yangjian.agent.protocol.ReportEntity> getReportEntityList() {
      if (reportEntityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(reportEntity_);
      } else {
        return reportEntityBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public int getReportEntityCount() {
      if (reportEntityBuilder_ == null) {
        return reportEntity_.size();
      } else {
        return reportEntityBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public com.yametech.yangjian.agent.protocol.ReportEntity getReportEntity(int index) {
      if (reportEntityBuilder_ == null) {
        return reportEntity_.get(index);
      } else {
        return reportEntityBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public Builder setReportEntity(
        int index, com.yametech.yangjian.agent.protocol.ReportEntity value) {
      if (reportEntityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReportEntityIsMutable();
        reportEntity_.set(index, value);
        onChanged();
      } else {
        reportEntityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public Builder setReportEntity(
        int index, com.yametech.yangjian.agent.protocol.ReportEntity.Builder builderForValue) {
      if (reportEntityBuilder_ == null) {
        ensureReportEntityIsMutable();
        reportEntity_.set(index, builderForValue.build());
        onChanged();
      } else {
        reportEntityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public Builder addReportEntity(com.yametech.yangjian.agent.protocol.ReportEntity value) {
      if (reportEntityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReportEntityIsMutable();
        reportEntity_.add(value);
        onChanged();
      } else {
        reportEntityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public Builder addReportEntity(
        int index, com.yametech.yangjian.agent.protocol.ReportEntity value) {
      if (reportEntityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReportEntityIsMutable();
        reportEntity_.add(index, value);
        onChanged();
      } else {
        reportEntityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public Builder addReportEntity(
        com.yametech.yangjian.agent.protocol.ReportEntity.Builder builderForValue) {
      if (reportEntityBuilder_ == null) {
        ensureReportEntityIsMutable();
        reportEntity_.add(builderForValue.build());
        onChanged();
      } else {
        reportEntityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public Builder addReportEntity(
        int index, com.yametech.yangjian.agent.protocol.ReportEntity.Builder builderForValue) {
      if (reportEntityBuilder_ == null) {
        ensureReportEntityIsMutable();
        reportEntity_.add(index, builderForValue.build());
        onChanged();
      } else {
        reportEntityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public Builder addAllReportEntity(
        java.lang.Iterable<? extends com.yametech.yangjian.agent.protocol.ReportEntity> values) {
      if (reportEntityBuilder_ == null) {
        ensureReportEntityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reportEntity_);
        onChanged();
      } else {
        reportEntityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public Builder clearReportEntity() {
      if (reportEntityBuilder_ == null) {
        reportEntity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        reportEntityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public Builder removeReportEntity(int index) {
      if (reportEntityBuilder_ == null) {
        ensureReportEntityIsMutable();
        reportEntity_.remove(index);
        onChanged();
      } else {
        reportEntityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public com.yametech.yangjian.agent.protocol.ReportEntity.Builder getReportEntityBuilder(
        int index) {
      return getReportEntityFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public com.yametech.yangjian.agent.protocol.ReportEntityOrBuilder getReportEntityOrBuilder(
        int index) {
      if (reportEntityBuilder_ == null) {
        return reportEntity_.get(index);  } else {
        return reportEntityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public java.util.List<? extends com.yametech.yangjian.agent.protocol.ReportEntityOrBuilder> 
         getReportEntityOrBuilderList() {
      if (reportEntityBuilder_ != null) {
        return reportEntityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(reportEntity_);
      }
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public com.yametech.yangjian.agent.protocol.ReportEntity.Builder addReportEntityBuilder() {
      return getReportEntityFieldBuilder().addBuilder(
          com.yametech.yangjian.agent.protocol.ReportEntity.getDefaultInstance());
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public com.yametech.yangjian.agent.protocol.ReportEntity.Builder addReportEntityBuilder(
        int index) {
      return getReportEntityFieldBuilder().addBuilder(
          index, com.yametech.yangjian.agent.protocol.ReportEntity.getDefaultInstance());
    }
    /**
     * <code>repeated .ReportEntity reportEntity = 1;</code>
     */
    public java.util.List<com.yametech.yangjian.agent.protocol.ReportEntity.Builder> 
         getReportEntityBuilderList() {
      return getReportEntityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yametech.yangjian.agent.protocol.ReportEntity, com.yametech.yangjian.agent.protocol.ReportEntity.Builder, com.yametech.yangjian.agent.protocol.ReportEntityOrBuilder> 
        getReportEntityFieldBuilder() {
      if (reportEntityBuilder_ == null) {
        reportEntityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.yametech.yangjian.agent.protocol.ReportEntity, com.yametech.yangjian.agent.protocol.ReportEntity.Builder, com.yametech.yangjian.agent.protocol.ReportEntityOrBuilder>(
                reportEntity_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        reportEntity_ = null;
      }
      return reportEntityBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReportRequest)
  }

  // @@protoc_insertion_point(class_scope:ReportRequest)
  private static final com.yametech.yangjian.agent.protocol.ReportRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yametech.yangjian.agent.protocol.ReportRequest();
  }

  public static com.yametech.yangjian.agent.protocol.ReportRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportRequest>
      PARSER = new com.google.protobuf.AbstractParser<ReportRequest>() {
    @java.lang.Override
    public ReportRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yametech.yangjian.agent.protocol.ReportRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

