// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package com.yametech.yangjian.agent.protocol;

public interface ReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ReportEntity reportEntity = 1;</code>
   */
  java.util.List<com.yametech.yangjian.agent.protocol.ReportEntity> 
      getReportEntityList();
  /**
   * <code>repeated .ReportEntity reportEntity = 1;</code>
   */
  com.yametech.yangjian.agent.protocol.ReportEntity getReportEntity(int index);
  /**
   * <code>repeated .ReportEntity reportEntity = 1;</code>
   */
  int getReportEntityCount();
  /**
   * <code>repeated .ReportEntity reportEntity = 1;</code>
   */
  java.util.List<? extends com.yametech.yangjian.agent.protocol.ReportEntityOrBuilder> 
      getReportEntityOrBuilderList();
  /**
   * <code>repeated .ReportEntity reportEntity = 1;</code>
   */
  com.yametech.yangjian.agent.protocol.ReportEntityOrBuilder getReportEntityOrBuilder(
      int index);
}
